version: '3.9'
services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    expose:
      - ${MYSQL_PORT}
    networks:
      - database
    volumes:
      - data_db:/var/lib/mysql
  phpmyadmin:
    container_name: pma
    platform: linux/x86_64
    image: phpmyadmin
    depends_on:
      - mysql
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MEMORY_LIMIT: 1G
      UPLOAD_LIMIT: 256M
      HIDE_PHP_VERSION: true
    ports:
      - ${PMA_PORT}:80
    networks:
      - database
  django:
    container_name: django
    platform: linux/x86_64
    image: microservice_app
    build: ./django
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn app.wsgi:application --bind 0.0.0.0:80" 
    depends_on:
      - mysql
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - .:/microservice
      - data_backend:/home/app/microservice/static
      - ./django:/home/app/webapp
    ports:
      - ${DJANGO_PORT}:80
    expose:
      - ${DJANGO_PORT}
    networks:
      - database
networks:
  database:
    driver: bridge
volumes:
  data_db:
  data_backend: