version: '3.7'
services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    networks:
      - db
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    container_name: pma
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: 'root'
networks:
  db:
volumes:
  db_data: