version: "3.9"
services:
  mysql:
    container_name: db-mysql
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    expose:
      - ${MYSQL_PORT}
    networks:
      - database
    volumes:
      - data_db:/var/lib/mysql
  phpmyadmin:
    container_name: db--phpmyadmin
    platform: linux/x86_64
    image: phpmyadmin
    depends_on:
      - mysql
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_PORT: ${MYSQL_PORT}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MEMORY_LIMIT: 1G
      UPLOAD_LIMIT: 256M
      HIDE_PHP_VERSION: "true"
    ports:
      - ${PMA_PORT}:80
    networks:
      - database
  rust:
    container_name: app-rust
    platform: linux/arm64/v8
    image: backend
    depends_on:
      - mysql
    restart: always
    environment:
      RUST_DB_URL: ${RUST_DB_URL}
      MYSQL_HOST: mysql
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 8000:8000
    expose:
      - "8000"
    networks:
      - database
      - backend
  sveltekit:
    container_name: app-vite-sveltekit
    platform: linux/x86_64
    build:
      context: ./
      dockerfile: ./sveltekit/dockerfile
    restart: always
    ports:
      - ${VITE_PORT}:3000
    expose:
      - ${VITE_PORT}
    networks:
      - backend
  webhook:
    container_name: github-webhook
    image: php:8.0-apache
    volumes:
      - ./webhook:/var/www/html/
    ports:
      - ${WEBHOOK_PORT}:80
    expose:
      - ${WEBHOOK_PORT}
networks:
  database:
    driver: bridge
  backend:
    driver: bridge
volumes:
  data_db:
