version: '3.7'
services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - '${DB_PORT}:3306'
    networks:
      - db
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    container_name: pma
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: '${DB_PORT}'
      PMA_USER: '${MYSQL_USER}'
      PMA_PASSWORD: '${MYSQL_PASSWORD}'
      MEMORY_LIMIT: 1G
      UPLOAD_LIMIT: 256M
      HIDE_PHP_VERSION: true
    ports:
      - '${PMA_PORT}:80'
    networks:
      - db
networks:
  db:
volumes:
  db_data: