version: '3.9'
services:
  database:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    expose:
      - ${MYSQL_PORT}
    networks:
      - database
    volumes:
      - data_db:/var/lib/mysql
  phpmyadmin:
    container_name: pma
    platform: linux/x86_64
    image: phpmyadmin
    depends_on:
      - database
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_PORT: ${MYSQL_PORT}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MEMORY_LIMIT: 1G
      UPLOAD_LIMIT: 256M
      HIDE_PHP_VERSION: true
    ports:
      - ${PMA_PORT}:80
    networks:
      - database
  backend:
    container_name: rust
    platform: linux/x86_64
    image: rust-backend
    depends_on:
      - database
    restart: always
    environment:
      RUST_DB_URL: ${RUST_DB_URL}
      MYSQL_HOST: mysql
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 8000:8000
    expose:
      - "8000" 
    networks:
      - database
      - backend
  frontend:
    container_name: vite
    platform: linux/x86_64
    build:
      context: ./
      dockerfile: ./sveltekit/dockerfile
    depends_on:
      - backend
    restart: always
    ports:
      - ${VITE_PORT}:4173
    expose:
      - ${VITE_PORT}
    networks:
      - backend
networks:
  database:
    driver: bridge
  backend:
    driver: bridge
volumes:
  data_db:
