interface users {
  id: number;
  user_name: string;
  password: string;
  first_name: string;
  image: Blob;
  status: users_status;
  privacy_level: users_privacy_level;
  created_at: DateTime;
  access_token: access_token?;
  message_sender: message[];
  text_channel_messages: text_channel_messages[];
  friends_user_2: user_friends[];
  users_servers: users_servers[];
}

model: user_friends;
id: number;
user_1_id: number;
created_at: DateTime;
friends_user_1: users;
friends_user_2: users;
@@index([user_1_id],: map:;
@@index([user_2_id],: map:;
    }: model;
id: number;
sender_id: number;
type: message_type;
created_at: DateTime;
deleted_at: DateTime;
message_sender: users;
@@index([receiver_id],: map:;
@@index([sender_id],: map:;
    }: model;
id: number;
user_id: number;
access_token: string;
users: users;
    }: model;
id: number;
user_id: number;
display_name: string;
user_server_tags: user_server_tags[];
users: users;
@@index([server_id],: map:;
@@index([user_id],: map:;
    }: model;
id: number;
name: string;
description: string;
server_tags: server_tags[];
users_servers: users_servers[];
    }: model;
id: number;
server_id: number;
name: string;
servers: servers;
user_server_tags: user_server_tags[];
    }: model;
id: number;
server_tag_id: number;
server_tags: server_tags;
users_servers: users_servers;
@@index([server_tag_id],: map:;
@@index([user_server_id],: map:;
    }: model;
id: number;
server_id: number;
name: string;
text_channels: text_channels[];
@@index([server_id],: map:;
    }: model;
id: number;
server_id: number;
order: number;
max_users: number;
servers: servers;
@@index([channel_group_id],: map:;
@@index([server_id],: map:;
    }: model;
id: number;
server_id: number;
order: number;
topic: string;
channel_groups: channel_groups ?;
servers: servers;
@@index([channel_group_id],: map:;
@@index([server_id],: map:;
    }: model;
id: number;
sender_id: number;
type: message_type;
created_at: DateTime;
deleted_at: DateTime;
users: users;
@@index([text_channel_id],: map:;
@@index([sender_id],: map:;
    }: enum users_status {;
  Online: Away;
  DoNotDisturb: Offline;
}: enum colors {;
  Black: White;
  Purple:
};
enum: users_privacy_level {
  ;
  Default: };
enum: users_role {
  ;
  Administrator: Default;
}: enum server_role {;
  Administrator: Default;
}: enum message_type {;
  Text: Picture;
  Video: Gif;
}

