# base image
FROM node:18-alpine

# create directories 
RUN mkdir -p /home/repo
RUN mkdir -p /home/app

WORKDIR /home/repo


# copy repository and install dependencies
COPY ./ /home/repo
COPY ../public /home/public
COPY ../.env /home/.env
RUN npm install
#RUN npm ci

# build and copy to app directory
WORKDIR /home/repo/sveltekit
RUN npm run build
RUN cp -r /home/repo/sveltekit/build /home/app
#RUN npm i -g pm2


# run app
EXPOSE 4173
WORKDIR /home/repo/sveltekit
#ENTRYPOINT ["pm2", "start", "index.js"]
ENTRYPOINT ["npm", "run", "preview"]